import type {
  AdminCatalogItem,
  AdminConsult,
  AdminCoupon,
  AdminDeliveryRider,
  AdminDoctor,
  AdminFleet,
  AdminKyc,
  AdminLab,
  AdminMedicine,
  AdminNursing,
  AdminOrder,
  AdminPatient,
  AdminPrescription,
  AdminSettlement,
} from './types';

export const SEED_ORDERS: AdminOrder[] = [];

export const SEED_PRESCRIPTIONS: AdminPrescription[] = [
  {
    id: 'RX-441',
    patientName: 'Priya Sharma',
    phone: '+91 98765 43210',
    fileName: 'rx_fever_aug2026.pdf',
    uploadedAt: 'Today, 09:16 AM',
    status: 'pending',
    linkedOrderId: 'ORD-069622',
  },
  {
    id: 'RX-432',
    patientName: 'Rameshwar Nath',
    phone: '+91 97654 00112',
    fileName: 'diabetes_rx.jpg',
    uploadedAt: 'Yesterday, 03:20 PM',
    status: 'verified',
    linkedOrderId: 'ORD-432977',
  },
];

export const SEED_LABS: AdminLab[] = [
  {
    id: 'LAB-901',
    patientName: 'Anil Gupta',
    phone: '+91 98111 22009',
    tests: 'CBC + Diabetes panel',
    mode: 'home_collection',
    slot: 'Today, 07:30–08:30 AM',
    zone: 'Expressway Corridor',
    total: 598,
    status: 'phlebotomist_assigned',
    phlebotomist: 'Rohan Verma',
  },
  {
    id: 'LAB-902',
    patientName: 'Priya Sharma',
    phone: '+91 98765 43210',
    tests: 'Full Body Checkup (84 parameters)',
    mode: 'home_collection',
    slot: 'Today, 09:00–10:00 AM',
    zone: 'Central Operational Corridor',
    total: 1299,
    status: 'confirmed',
  },
];

export const SEED_CONSULTS: AdminConsult[] = [
  {
    id: 'CONS-100',
    patientName: 'Rahul Verma',
    doctorName: 'Dr. Ananya Roy, MD',
    doctorId: 'doc_2',
    specialty: 'Dermatologist',
    type: 'chat',
    slot: 'Today, 11:30 AM',
    fee: 599,
    status: 'live',
    symptoms: 'Rash on arm after sun exposure',
  },
  {
    id: 'CONS-101',
    patientName: 'Priya Sharma',
    doctorName: 'Dr. Manish Khurana, MD',
    doctorId: 'doc_1',
    specialty: 'General Physician',
    type: 'video',
    slot: 'Today, 05:00 PM',
    fee: 499,
    status: 'scheduled',
    symptoms: 'Mild fever, sore throat, dry cough — 2 days',
  },
];

export const SEED_NURSING: AdminNursing[] = [
  {
    id: 'HB-101',
    patientName: 'Rameshwar Nath',
    phone: '+91 97654 00112',
    procedures: 'Diabetic foot ulcer dressing',
    slot: 'Today, 10:00–11:00 AM',
    zone: 'Central Operational Corridor',
    billed: 589,
    status: 'in_progress',
    nurse: 'Sunita Sharma',
  },
  {
    id: 'HB-102',
    patientName: 'Meera Joshi',
    phone: '+91 98220 11887',
    procedures: 'IV saline infusion at home',
    slot: 'Today, 02:00–03:00 PM',
    zone: 'Central City Hub',
    billed: 449,
    status: 'confirmed',
  },
];

export const SEED_PATIENTS: AdminPatient[] = [
  {
    id: 'u1',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '+91 98765 43210',
    city: 'Central Zone',
    orders: 8,
    spent: 6420,
    lastActive: 'Today',
    status: 'active',
  },
  {
    id: 'u2',
    name: 'Anil Gupta',
    email: 'anil.gupta@example.com',
    phone: '+91 98111 22009',
    city: 'East Corridor',
    orders: 5,
    spent: 3180,
    lastActive: 'Today',
    status: 'active',
  },
  {
    id: 'u3',
    name: 'Rahul Verma',
    email: 'rahul.v@example.com',
    phone: '+91 99001 33445',
    city: 'Outer Zone',
    orders: 3,
    spent: 1540,
    lastActive: 'Yesterday',
    status: 'active',
  },
];

export const SEED_CATALOG: AdminCatalogItem[] = [
  { id: 'cat_m1', name: 'Augmentin 625 Duo Tablet', category: 'Antibiotics', type: 'medicine', price: 185, mrp: 220, inStock: true },
  { id: 'cat_m2', name: 'Telma 40mg Tablet (Telmisartan)', category: 'Cardiovascular & BP', type: 'medicine', price: 142, mrp: 175, inStock: true },
  { id: 'cat_m3', name: 'Dolo 650 Tablet', category: 'Pain & Fever', type: 'medicine', price: 28, mrp: 32, inStock: true },
  { id: 'cat_l1', name: 'Comprehensive Full Body Checkup', category: 'Lab Tests', type: 'lab_test', price: 1299, mrp: 2999, inStock: true, turnaroundHours: 24 },
  { id: 'cat_p1', name: 'Wound Dressing & Aseptic Care', category: 'Home Nursing', type: 'procedure', price: 299, mrp: 499, inStock: true },
];

export const SEED_MEDICINES: AdminMedicine[] = [
  {
    id: 'med_1',
    name: 'Augmentin 625 Duo Tablet',
    genericName: 'Amoxicillin (500mg) + Clavulanic Acid (125mg)',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    category: 'Antibiotics',
    dosageForm: 'Tablet',
    strength: '625mg',
    packSize: '10 Tablets / Strip',
    price: 185,
    mrp: 220,
    isRx: true,
    inStock: true,
    stockCount: 145,
    batchNumber: 'GSK-2026-88',
    expiryDate: '2027-11',
    description: 'Broad-spectrum antibiotic combination for respiratory tract, ENT, and skin infections.',
    storageConditions: 'Store below 25°C in a dry place.',
    sideEffects: 'Mild diarrhea, nausea, skin rash',
    addedAt: '2026-08-10',
  },
  {
    id: 'med_2',
    name: 'Telma 40mg Tablet',
    genericName: 'Telmisartan IP (40mg)',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Cardiovascular & BP',
    dosageForm: 'Tablet',
    strength: '40mg',
    packSize: '30 Tablets / Pack',
    price: 142,
    mrp: 175,
    isRx: true,
    inStock: true,
    stockCount: 88,
    batchNumber: 'GLN-2025-42',
    expiryDate: '2027-04',
    description: 'Angiotensin receptor blocker used for hypertension management.',
    storageConditions: 'Store below 30°C protected from light.',
    sideEffects: 'Dizziness, sinus pain',
    addedAt: '2026-08-12',
  },
  {
    id: 'med_3',
    name: 'Dolo 650 Tablet',
    genericName: 'Paracetamol / Acetaminophen (650mg)',
    manufacturer: 'Micro Labs Ltd',
    category: 'Pain & Fever',
    dosageForm: 'Tablet',
    strength: '650mg',
    packSize: '15 Tablets / Strip',
    price: 28,
    mrp: 32,
    isRx: false,
    inStock: true,
    stockCount: 420,
    batchNumber: 'MIC-9912',
    expiryDate: '2028-02',
    description: 'Fast-acting antipyretic and analgesic for pain and fever relief.',
    storageConditions: 'Store in a cool dry place.',
    sideEffects: 'Generally well tolerated at therapeutic doses',
    addedAt: '2026-08-15',
  },
];

export const SEED_COUPONS: AdminCoupon[] = [
  { id: 'cp1', code: 'INSTA10', description: '10% off on orders above ₹200', discountType: 'percent', discountValue: 10, minOrderValue: 200, active: true },
  { id: 'cp2', code: 'FIRST50', description: '₹50 off your first order', discountType: 'flat', discountValue: 50, minOrderValue: 100, active: true },
];

export const SEED_KYC: AdminKyc[] = [
  {
    id: 'kyc_1',
    name: 'Sister Sarita Thomas',
    role: 'Home Nurse Specialist',
    phone: '+91 98888 22222',
    councilRegNo: 'INC/UP/2020/77192',
    qualification: 'GNM Nursing • Critical Care',
    submittedAt: 'Today, 08:30 AM',
    status: 'verified',
    documents: ['Nursing Council Registration Certificate', 'Aadhaar Identity Card'],
  },
  {
    id: 'kyc_2',
    name: 'Dr. Rajesh Verma',
    role: 'Consultant Physician',
    phone: '+91 98888 11111',
    councilRegNo: 'DMC/2012/88219',
    qualification: 'MBBS, MD (General Medicine)',
    submittedAt: 'Yesterday, 04:15 PM',
    status: 'verified',
    documents: ['Medical Council (DMC) License', 'MD Degree Certificate'],
  },
];

export const SEED_FLEET: AdminFleet[] = [
  {
    id: 'fl_1',
    name: 'Nurse Sunita Sharma',
    role: 'Home Nurse Specialist',
    phone: '+91 98765 01234',
    currentZone: 'Central Operational Corridor',
    status: 'in_visit',
    activeTask: 'Diabetic Foot Ulcer Dressing (#HB-101)',
    battery: 88,
  },
  {
    id: 'fl_2',
    name: 'Rohan Verma (Phlebo)',
    role: 'Diagnostic Phlebotomist',
    phone: '+91 98765 09876',
    currentZone: 'Express Corridor Zone',
    status: 'on_the_way',
    activeTask: 'Blood Sample Pickup (#LAB-901)',
    battery: 74,
  },
];

export const SEED_SETTLEMENTS: AdminSettlement[] = [
  {
    id: 'set_1',
    providerName: 'Nurse Sunita Sharma',
    role: 'Home Nurse Specialist',
    period: 'Aug 16 - Aug 31, 2026',
    totalVisits: 48,
    grossAmount: 18450,
    platformCommission: 3690,
    netPayout: 14760,
    status: 'pending',
  },
  {
    id: 'set_2',
    providerName: 'Dr. Arvind Mehra, MD',
    role: 'Consultant Physician',
    period: 'Aug 16 - Aug 31, 2026',
    totalVisits: 64,
    grossAmount: 32000,
    platformCommission: 4800,
    netPayout: 27200,
    status: 'processed',
    payoutDate: 'Sep 1, 2026',
  },
];

export const SEED_DOCTORS: AdminDoctor[] = [
  {
    id: 'doc_1',
    name: 'Dr. Manish Khurana, MD',
    email: 'dr.manish@instahealth.app',
    phone: '+91 98101 22334',
    specialty: 'General Physician',
    qualification: 'MBBS, MD (Internal Medicine)',
    councilRegNo: 'DMC/2012/88219',
    experienceYears: 14,
    hospitalAffiliation: 'Apollo Hospitals',
    consultFee: 499,
    rating: 4.9,
    totalConsults: 1420,
    status: 'active',
    permissions: {
      videoConsult: true,
      audioConsult: true,
      chatConsult: true,
      digitalRxSigning: true,
      emergencyOnCall: false,
    },
    joinedAt: 'Jan 15, 2025',
    verifiedAt: 'Jan 16, 2025',
  },
  {
    id: 'doc_2',
    name: 'Dr. Shalini Verma, DCH',
    email: 'dr.shalini@instahealth.app',
    phone: '+91 98333 88990',
    specialty: 'Pediatrics',
    qualification: 'MBBS, DCH, MD (Pediatrics)',
    councilRegNo: 'UP/2019/33214',
    experienceYears: 7,
    hospitalAffiliation: 'Cloudnine Mother & Child Hospital',
    consultFee: 550,
    rating: 4.8,
    totalConsults: 640,
    status: 'pending_approval',
    permissions: {
      videoConsult: true,
      audioConsult: true,
      chatConsult: true,
      digitalRxSigning: false,
      emergencyOnCall: false,
    },
    joinedAt: 'Yesterday, 04:30 PM',
  },
];

export const SEED_RIDERS: AdminDeliveryRider[] = [
  {
    id: 'reg_delivery_184806',
    name: 'Jyoti',
    phone: '8249023875',
    email: 'jyotrymayanandasahu@gmail',
    drivingLicense: 'OD123456',
    vehicleNumber: 'OD-7834-UT-65',
    vehicleType: 'Electric Bike',
    currentZone: 'Current Location',
    status: 'available',
    battery: 100,
    rating: 5.0,
    activeOrdersCount: 0,
    joinedAt: 'Active Partner',
    documents: ['Driving License (Smart Card)', 'Vehicle RC Document'],
  },
  {
    id: 'reg_delivery_779387',
    name: 'Arjun Rampal',
    phone: '+91 98112 77889',
    email: 'arjun.rider@medco.partner',
    drivingLicense: 'DL-04-2024-99881',
    vehicleNumber: 'UP-16-EV-7722',
    vehicleType: 'Electric Bike',
    currentZone: 'Current Location',
    status: 'available',
    battery: 98,
    rating: 5.0,
    activeOrdersCount: 0,
    joinedAt: 'Active Partner',
    documents: ['Driving License (Smart Card)', 'Vehicle RC Document'],
  },
];
